name: onetwotrail

version: 1.12.0+110

dependencies:
  flutter:
    sdk: "flutter"
  flutter_localizations:
    sdk: "flutter"
  animations: "^2.0.0"
  auto_size_text: "^3.0.0"
  cached_network_image: "^3.4.1"
  carousel_slider: "^5.0.0"
  cupertino_icons: "^1.0.0"
  debounce_throttle: "^2.0.0"
  device_info_plus: "^10.0.0"
  flavor: "^2.0.0"
  flutter_facebook_auth: "^7.1.1"
  flutter_libphonenumber: "^2.5.1"
  flutter_masked_text2: "^0.9.1"
  flutter_slidable: "^4.0.0"
  flutter_staggered_grid_view: "^0.7.0"
  fluttertoast: "^8.2.12"
  font_awesome_flutter: "^10.0.0"
  google_map_polyline_new: "^0.3.0+2"
  google_maps_flutter: "^2.14.0"
  http: "^1.3.0"
  image_picker: "^1.1.2"
  intl: "^0.20.2"
  intl_phone_number_input: "^0.7.4"
  modal_bottom_sheet: "^3.0.0"
  provider: "^6.1.2"
  shared_preferences: "^2.5.3"
  shimmer: "^3.0.0"
  sign_in_with_apple: "^7.0.1"
  snapping_sheet: "^3.1.0"
  substring_highlight: "^1.0.33"
  url_launcher: "^6.3.1"
  logging: "^1.3.0"
  datadog_flutter_plugin: "^2.11.0"
  package_info_plus: "^8.3.0"

dev_dependencies:
  analyzer: "^7.3.0"
  build_runner: "^2.4.15"
  faker: "^2.0.0"
  flutter_test:
    sdk: "flutter"
  integration_test:
    sdk: "flutter"
  mockito: "^5.4.5"

environment:
  sdk: ">=3.0.0 <4.0.0"
flutter:
  generate: true
  assets:
    - assets/background_images/
    - assets/experience-features/
    - assets/help/
    - assets/icons/
    - assets/icons/logo/
    - assets/landing_images/
    - assets/main_filter/
    - assets/more_information/
    - assets/my_trails/
    - assets/on_boarding_images/
    - assets/report_issue/
    - assets/splash/
    - assets/trail_component_menu/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true
